#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    count=0
    state=0
    
    for i in range(len(path)):
        if(path[i]=='U'):
            steps=steps-1
            state=state+1
        elif(path[i]=='D'):
            steps=steps-1
            if(state==0):
                count=count+1
            state=state-1
    if(steps==0):
        return count
            
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
